name: ci pipeline

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v5

      - name: Set up Node.js
        uses: actions/setup-node@v4  # Препоръчвам v4, по-нова е
        with:
          node-version: 18          # Node 16 е вече стара, по-добре ползвай 18 или 20

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test